FROM node:14
WORKDIR /usr/src/app

# Copy the desired .json files from the src directory
# into the dockerbuild folder each time before building
COPY src/package*.json ./

# For testing
#RUN npm install
# For production
RUN npm ci --only=production

# Instead of this, just set with -v at run-time...
#COPY src .

# Instead of this, just set with -p at run-time...
#EXPOSE 3029/tcp

# Run once:
CMD [ "node", "." ]
